Repository 47degrees/sbt-microsites, pull requests merged in 2019-12, with the labels that each got.

#383 Update sbt version in Travis, micrositeDocumentationUrl
  .travis.yml
  docs/docs/docs/getting-started.md
  project/ProjectPlugin.scala
Labels: 1.0.0

#381 Update scalatest to 3.1.0
  project/ProjectPlugin.scala
  src/test/scala/microsites/DocsLayoutTest.scala
  src/test/scala/microsites/HomeLayoutTest.scala
  src/test/scala/microsites/LayoutTest.scala
  src/test/scala/microsites/MenuPartialLayoutTest.scala
  src/test/scala/microsites/PageLayoutTest.scala
Labels: 1.0.0

#382 Release 1.0.0
  version.sbt
Labels: 1.0.0

#380 Update scalactic to 3.1.0
  project/ProjectPlugin.scala
Labels: 1.0.0

#385 Release version 1.0.0
  version.sbt
Labels: 1.0.0

#394 Tell hljs the language of code blocks so it doesn't have to guess
  src/main/scala/microsites/layouts/Layout.scala
Labels: enhancement

#399 Simplify deployment - Improve docs
  .travis.yml
  docs/docs/docs/build-the-microsite.md
  docs/docs/docs/customize.md
  docs/docs/docs/getting-started.md
  docs/docs/docs/layouts.md
  docs/docs/docs/publish-with-travis.md
  docs/docs/docs/settings.md
Labels: docs
