Repository 47degrees/sbt-microsites, pull requests merged in 2020-04, with the labels that each got.

#459 Update actions, documentation templates and configuration files to v0.4.0
  .github/labels.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/bot-prs-auto-approve.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/update-labels.yml
  .gitignore
  .mergify.yml
  .travis.yml
  README.md
  build.sbt
  docs/AUTHORS.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/LICENSE.md
  docs/NOTICE.md
  project/ProjectPlugin.scala
  project/plugins.sbt
  secret_key.asc.enc
  src/main/scala/microsites/MicrositeKeys.scala
  version.sbt
Labels: auto-update

#460 Update CHANGELOG.md
  CHANGELOG.md
Labels: auto-changelog, auto-update

#462 Update actions, documentation templates and configuration files to v0.4.1
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: auto-update

#463 Update actions, documentation templates and configuration files to v0.5.0
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .mergify.yml
Labels: auto-update

#464 Update CHANGELOG.md
  CHANGELOG.md
Labels: auto-changelog

#465 Removes Sbt-org-policies Dependency
  build.sbt
  docs/docs/docs/intro.md
  project/ProjectPlugin.scala
  project/plugins.sbt
  src/main/scala/microsites/Exceptions.scala
  src/main/scala/microsites/MicrositeKeys.scala
  src/main/scala/microsites/github/Config.scala
  src/main/scala/microsites/github/GitHubOps.scala
  src/main/scala/microsites/ioops/FileReader.scala
  src/main/scala/microsites/ioops/FileWriter.scala
  src/main/scala/microsites/ioops/IOUtils.scala
  src/main/scala/microsites/ioops/ioops.scala
  src/main/scala/microsites/layouts/Layout.scala
  src/main/scala/microsites/util/MicrositeHelper.scala
  src/main/scala/microsites/util/YamlFormats.scala
Labels: breaking-change

#466 Update documentation and other files
  src/main/scala/microsites/Exceptions.scala
  src/main/scala/microsites/MicrositeKeys.scala
  src/main/scala/microsites/MicrositesPlugin.scala
  src/main/scala/microsites/github/Config.scala
  src/main/scala/microsites/github/GitHubOps.scala
  src/main/scala/microsites/ioops/FileReader.scala
  src/main/scala/microsites/ioops/FileWriter.scala
  src/main/scala/microsites/ioops/IOUtils.scala
  src/main/scala/microsites/ioops/ioops.scala
  src/main/scala/microsites/layouts/DocsLayout.scala
  src/main/scala/microsites/layouts/FeaturesLayout.scala
  src/main/scala/microsites/layouts/HomeLayout.scala
  src/main/scala/microsites/layouts/Layout.scala
  src/main/scala/microsites/layouts/MenuPartialLayout.scala
  src/main/scala/microsites/layouts/PageLayout.scala
  src/main/scala/microsites/microsites.scala
  src/main/scala/microsites/util/BuildHelper.scala
  src/main/scala/microsites/util/MicrositeHelper.scala
  src/main/scala/microsites/util/YamlFormats.scala
  src/test/scala/microsites/DocsLayoutTest.scala
  src/test/scala/microsites/HomeLayoutTest.scala
  src/test/scala/microsites/LayoutTest.scala
  src/test/scala/microsites/MenuPartialLayoutTest.scala
  src/test/scala/microsites/PageLayoutTest.scala
  src/test/scala/microsites/util/Arbitraries.scala
Labels: auto-documentation

#467 Update CHANGELOG.md
  CHANGELOG.md
Labels: auto-changelog

#473 Update documentation and other files
  AUTHORS.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  NOTICE.md
  src/main/scala/microsites/Exceptions.scala
  src/main/scala/microsites/MicrositeKeys.scala
  src/main/scala/microsites/MicrositesPlugin.scala
  src/main/scala/microsites/github/Config.scala
  src/main/scala/microsites/github/GitHubOps.scala
  src/main/scala/microsites/ioops/FileReader.scala
  src/main/scala/microsites/ioops/FileWriter.scala
  src/main/scala/microsites/ioops/IOUtils.scala
  src/main/scala/microsites/ioops/ioops.scala
  src/main/scala/microsites/layouts/DocsLayout.scala
  src/main/scala/microsites/layouts/FeaturesLayout.scala
  src/main/scala/microsites/layouts/HomeLayout.scala
  src/main/scala/microsites/layouts/Layout.scala
  src/main/scala/microsites/layouts/MenuPartialLayout.scala
  src/main/scala/microsites/layouts/PageLayout.scala
  src/main/scala/microsites/microsites.scala
  src/main/scala/microsites/util/BuildHelper.scala
  src/main/scala/microsites/util/MicrositeHelper.scala
  src/main/scala/microsites/util/YamlFormats.scala
  src/test/scala/microsites/DocsLayoutTest.scala
  src/test/scala/microsites/HomeLayoutTest.scala
  src/test/scala/microsites/LayoutTest.scala
  src/test/scala/microsites/MenuPartialLayoutTest.scala
  src/test/scala/microsites/PageLayoutTest.scala
  src/test/scala/microsites/util/Arbitraries.scala
Labels: auto-documentation
